import { _mock } from './_mock';

// ----------------------------------------------------------------------

const PROJECT_CATEGORIES = ['workflow-building', 'ai', 'automation', 'integration', 'community-node', 'data-transformation', 'core'];
const PROJECT_TAGS = [
  'workflow-building', 'ai', 'code', 'crypto', 'embeddings', 'html', 'http-request',
  'loop-over-items', 'openai', 'send-email', 'node', 'community-node', 'rest-api',
  'oauth2', 'webhook', 'data-transformation', 'google-docs', 'markdown', 'core',
  'deployment', 'credentials', 'tutorial', 'product-feedback', 'gemini', 'n8n-node',
];

const PROJECT_TITLES = [
  'About the Built with n8n category',
  'Auto Publishing Agent: Multi-platform image + AI copy workflow in n8n',
  'Built a fully controllable AI blog writing system in n8n. Here\'s a breakdown of how it works. [Template provided!]',
  'Check out my SEC Crypto Investments AI Analysis workflow',
  'New Community Node: Image Hasher - Automatic Perceptual Image Hashing',
  'New Community Node: Markdown to Google Docs - Advanced Document Automation',
  'Built a community node for the session ID problem',
  '[Use Case] Built an AI Agent That Generates SEO + Emotionally Optimized Content for Blog, Social, Newsletter, Landing Pages (GEO)',
  '[Free] Get Email Alerts When Your Shopify/Inventory Stock is Low',
  'A standalone node for testing email workflow',
  'I have released version 2 of my n8n_nginx auto installer!',
  'Turning Lead Conversations into Seamless Automation with n8n',
  'Hardened Docker Stack - NGINX Reverse Proxy and PostgreSQL',
  'Local n8n Cloud Dashboard',
  'My Udemy Course Free for a limited few',
  '🎁 Giveaway - 1 Month of n8n Cloud Pro Plan [Coupon Code]',
  'AI-Powered Real Estate Chatbot: Intelligent Lead Management & Appointment',
  'AI Product Video Ad Generator (Text-to-Speech + Video with Wavespeed & ElevenLabs)',
  'Custom: Wechat official Account[微信公众号] Node',
  '.eml file analyze',
  '[New Node] MusicGPT - AI Music Generation',
  'Google Gemini 3 Pro Wrote My n8n Workflow 🤯',
  'Free n8n Automation Setup for 5 Small Businesses',
  'Excited to share my latest automation workflow project',
  '🌿 AI Nutritionist: A workflow that plans meals based on your Blood Pressure data',
  'Twilio WhatsApp ContentSid template sending as plain text from n8n (no buttons)',
  '🔥 Automate Airbnb Guest Support with AI — Boost Efficiency Instantly!',
  '📢 Monitor n8n releases and get notifications for new versions',
  'N8n, nginx, Let\'s Encrypt, PostgreSQL install nightmare - so I built a script to do it all in 10 minutes',
  'Built an AI pipeline that turns text into full comic book storyboards',
  'Hardware + Automation: exploring a co-creation opportunity with n8n',
  'Automated WooCommerce Product Ranking Optimization',
  'Yahoo Finance! - Fetch Stock & Options Data with n8n',
  'Zoho Calendar Community Node',
  'Anyone Integrating AI Image Generation Tools Into n8n?',
  'Community nodes directory - NCNodes',
  'Why understanding business tools (not just n8n nodes) matters',
  'Procurement AI Agent',
  'SEO internal Linking visualizations with n8n',
  'I\'m trying to send .html to Whatsapp using Z-API, but doesn\'t work',
  'N8n workflow: update check & email notification',
  'Sales Team reach out for Enterprise',
];

const PROJECT_DESCRIPTIONS = [
  'This is a category for showing off the projects that you\'ve built with n8n. Everyone is invited to ask questions to the authors of the topics about their projects. Examples of posts that can be shared here include product demos, workflow templates, community nodes, and automation solutions.',
  'Created a multi-platform publishing agent that generates AI-powered copy and images, then automatically publishes to multiple social media platforms. Supports custom scheduling and content optimization.',
  'A fully controllable AI blog writing system with customizable templates, SEO optimization, and automated publishing. Includes intelligent content generation, fact-checking, and multiple output formats.',
  'Analyze SEC crypto investment data using AI. This workflow automatically fetches SEC filings, processes them with embeddings, and sends email alerts with investment insights and recommendations.',
  'Automatic perceptual image hashing node for duplicate detection and image similarity comparison. Perfect for content moderation and digital asset management.',
  'Advanced document automation tool that converts Markdown to Google Docs with formatting preservation, table of contents generation, and custom styling options.',
  'Solves the session ID problem in n8n workflows with a custom community node. Maintains session state across workflow executions for complex multi-step processes.',
  'AI-powered content generation agent that creates SEO and emotionally optimized content for blogs, social media, newsletters, and landing pages. Includes sentiment analysis and keyword optimization.',
  'Get instant email notifications when your Shopify or inventory stock levels drop below threshold. Automated inventory monitoring with customizable alerts.',
  'A standalone testing node for email workflows. Test your email templates, content, and delivery without sending actual emails. Perfect for development and debugging.',
  'Version 2 of the automatic installer for n8n with nginx. One command installation including SSL certificates, database setup, and automatic updates.',
  'Convert lead conversations into seamless automation. This workflow captures, analyzes, and routes leads automatically based on conversation context and sentiment.',
  'Production-ready Docker stack with hardened security. Includes NGINX reverse proxy, PostgreSQL database, SSL certificates, and automated backups.',
  'Self-hosted dashboard for managing n8n Cloud instances locally. Monitor workflows, executions, and system health from a beautiful local interface.',
  'Complete Udemy course on n8n automation. Covers basics to advanced topics including AI integration, custom nodes, and production deployment.',
  'Limited time giveaway of n8n Cloud Pro Plan. Enter to win 1 month of premium features including advanced scheduling and team collaboration.',
  'AI-powered chatbot for real estate. Handles lead qualification, appointment scheduling, property recommendations, and follow-up communications automatically.',
  'Generate product video ads automatically. Converts text descriptions to speech using ElevenLabs, creates videos with Wavespeed, and outputs ready-to-use ad content.',
  'Custom community node for WeChat Official Account integration. Send messages, handle webhooks, and automate WeChat workflows.',
  'Analyze .eml email files to extract attachments, headers, body content, and metadata. Perfect for email processing and automation workflows.',
  'AI-powered music generation node using MusicGPT. Create background music, jingles, and soundtracks based on text descriptions.',
  'Google Gemini 3 Pro AI wrote an entire n8n workflow. Demonstrates the power of AI-assisted automation development with natural language instructions.',
  'Offering free automation setup for 5 small businesses. Includes consultation, workflow design, implementation, and 30 days of support.',
  'Latest automation workflow project combining multiple AI services for enhanced productivity. Features smart routing, data processing, and intelligent notifications.',
  'AI Nutritionist workflow that creates personalized meal plans based on blood pressure data. Integrates with health tracking apps and generates shopping lists.',
  'Send WhatsApp messages with ContentSid templates from n8n. Troubleshooting guide for formatting issues and button display problems.',
  'Automate Airbnb guest support with AI responses. Handle check-in questions, provide property information, and manage guest requests 24/7.',
  'Automated monitoring system for n8n releases. Get instant notifications via email, Slack, or Discord when new versions are available.',
  'Complete installation script for n8n with nginx, Let\'s Encrypt SSL, and PostgreSQL. Eliminates all the pain points of manual setup.',
  'AI pipeline that converts text stories into full comic book storyboards. Includes character generation, scene composition, and panel layout.',
  'Exploring hardware automation opportunities. Connect physical devices with n8n workflows for IoT and smart home applications.',
  'Optimize WooCommerce product rankings automatically. Uses AI to analyze sales data, customer behavior, and market trends.',
  'Fetch real-time stock and options data from Yahoo Finance. Includes technical indicators, price alerts, and portfolio tracking.',
  'Community node for Zoho Calendar integration. Create events, manage schedules, and sync with other calendar services.',
  'Discussion about integrating AI image generation tools like DALL-E, Midjourney, and Stable Diffusion into n8n workflows.',
  'Comprehensive directory of community nodes with ratings, usage stats, and installation guides. Over 500 nodes catalogued.',
  'Understanding business tools and processes is just as important as technical n8n knowledge. Discussion on business automation strategy.',
  'AI-powered procurement agent that handles supplier management, purchase orders, and inventory optimization automatically.',
  'Visualize internal linking structure for SEO optimization. Analyzes website pages and generates interactive link graphs.',
  'Troubleshooting guide for sending HTML content to WhatsApp using Z-API. Includes formatting tips and workarounds.',
  'Automated update checker for n8n workflows. Monitors workflow changes and sends email notifications with changelogs.',
  'Enterprise sales team information and contact details. Get in touch for custom solutions, volume licensing, and dedicated support.',
];

// ----------------------------------------------------------------------

export const _builtWith = [...Array(42)].map((_, index) => ({
  id: `built-with-${index + 1}`,
  title: PROJECT_TITLES[index],
  description: PROJECT_DESCRIPTIONS[index],
  excerpt: `${PROJECT_DESCRIPTIONS[index].substring(0, 150)}...`,
  category: PROJECT_CATEGORIES[index % PROJECT_CATEGORIES.length],
  isPinned: index === 0, // First one is pinned
  isFeatured: index < 5, // First 5 are featured
  hasTemplate: [1, 2, 7, 14, 32].includes(index), // Some have templates
  author: {
    id: _mock.id(index + 600),
    name: _mock.fullName(index),
    avatarUrl: _mock.image.avatar(index),
    role: index % 8 === 0 ? 'Community Expert' : 'Community Member',
  },
  participants: [...Array(Math.min(4, Math.floor(Math.random() * 5) + 1))].map((__, idx) => ({
    id: _mock.id(index * 10 + idx + 700),
    name: _mock.fullName(index * 10 + idx),
    avatarUrl: _mock.image.avatar(index * 10 + idx),
    role: ['Developer', 'Expert', 'Member'][idx % 3],
    status: idx % 3 === 0 ? "This user's public profile is hidden." : 'Active community member',
    posts: Math.floor(Math.random() * 300) + 10,
    reputation: Math.floor(Math.random() * 3000) + 100,
  })),
  tags: [
    [],
    ['ai', 'workflow-building', 'workflow-templates'],
    ['workflow-building'],
    ['ai', 'code', 'crypto', 'embeddings', 'html', 'http-request', 'loop-over-items', 'openai', 'send-email'],
    ['node'],
    ['community-node', 'data-transformation', 'google-docs', 'markdown'],
    ['community-node'],
    ['core', 'workflow-building'],
    [],
    ['community-node'],
    [],
    [],
    [],
    [],
    ['core', 'credentials', 'data-transformation', 'deployment', 'http-request', 'node', 'openai', 'tutorial', 'webhook', 'workflow-building'],
    [],
    [],
    [],
    [],
    ['workflow-building'],
    ['ai', 'community-node'],
    ['gemini', 'n8n-node'],
    ['workflow-building'],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    ['data-transformation', 'node'],
    [],
    ['data-transformation', 'rest-api', 'workflow-building'],
    ['node'],
    ['core'],
    ['ai', 'community-node', 'product-feedback'],
    [],
    [],
    [],
    [],
    [],
  ][index] || [],
  replies: [2, 0, 1, 2, 3, 33, 0, 9, 0, 1, 0, 4, 3, 2, 11, 18, 0, 2, 6, 2, 0, 0, 8, 0, 1, 0, 1, 1, 0, 2, 2, 1, 3, 4, 1, 10, 1, 0, 3, 3, 3, 1][index] || 0,
  views: [4100, 5, 297, 52, 113, 1500, 20, 1200, 9, 65, 28, 77, 85, 89, 1200, 294, 63, 323, 1700, 479, 62, 187, 661, 69, 87, 44, 399, 84, 57, 111, 35, 34, 481, 747, 90, 16500, 72, 82, 773, 42, 154, 95][index] || 10,
  publishedAt: _mock.time(index),
  createdAt: _mock.time(index),
  lastActivity: ['Aug 15', '2h', '19h', '23h', '2d', '2d', '3d', '3d', '3d', '4d', '4d', '4d', '5d', '5d', '5d', '5d', '6d', '7d', '7d', '7d', '9d', '9d', '9d', '10d', '10d', '11d', '12d', '12d', '12d', '13d', '16d', '17d', '20d', '21d', '21d', '22d', '23d', '23d', '24d', '24d', '24d', '25d'][index] || '1d',
}));

